package ed.inf.adbs.minibase.Operator;

/**
 * The Operator class is an abstract base class for various types of operators
 * used in the query execution process. It provides a common interface for
 * interacting with operators, such as retrieving the next tuple, resetting
 * the operator state, and dumping the output.
 * @author jackson-zhou
 */
public abstract class Operator {

	/**
	 * Retrieves the next tuple from the operator.
	 * Concrete subclasses of Operator should implement this method to define
	 * their specific behavior for fetching the next tuple in the query execution process.
	 *
	 * @return The next Tuple object from the operator or null if there are no more tuples.
	 */
	public abstract Tuple getNextTuple();

	/**
	 * Resets the operator's state.
	 * Concrete subclasses of Operator should implement this method to define
	 * their specific behavior for resetting the operator's state, typically to
	 * the initial state before any tuples were processed.
	 */
	public abstract void reset();

	/**
	 * Dumps the output of the operator.
	 * Concrete subclasses of Operator should implement this method to define
	 * their specific behavior for printing the output of the operator, usually
	 * by iterating through the tuples generated by the operator and printing them.
	 */
	public abstract void dump();
}

